### ISSUE TITLE
Click through to definitions seems broken.

### ISSUE THREAD

**Issue by louiidev** [pherrymason/c3-lsp#36]
**Describe the bug**
When Clicking through to a definition, the editor is unable to open the file.

**To Reproduce**
1. Go to any .c3 file with an import module
2. Click on the imported module member/struct/variable
3. The editor will display an error:
The editor could not be opened due to an unexpected error: Unable to resolve resource C:%5CUsers%5Clouis%5Cc_dev%5Coogabooga%5Csrc%5Centity.c3

Obviously the path is different depending on the file its trying to open.

**Expected behavior**
The module/file opens up in a new tab or goes to the tab if previously opened already.

**Screenshots**
![Screenshot 2024-08-02 114639](https://github.com/user-attachments/assets/2d42f2ea-da07-4297-85a2-666289faa8ca)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Editor: Visual Studio Code
 - Version: c3-lsp-client-0.0.2

**Comment by pherrymason** [comment]
Seems to affect Windows.

How I see other LSP servers work with paths on Windows:

```
Params: {
    "uri": "file:///D:/projects/c3-lsp/server/internal/lsp/project_state/version.go",
    "diagnostics": []
}
```

How C3-LSP sends paths currently:
```
{
      "uri":"D:\\projects\\c3-lsp\\assets\\c3-demo\\foobar\\foo.c3",
      "range":{"start":{"line":0,"character":7},
      "end":{"line":0,"character":13}
}
```

**Comment by pherrymason** [comment]
Fixed in branch for 0.0.7

**Comment by louiidev** [comment]
Still encountering the issue after the update but the error path is slightly different..

![Screenshot 2024-08-03 183603](https://github.com/user-attachments/assets/657435a0-638c-4e74-8d62-c4a92f8742e8)

**Comment by pherrymason** [comment]
Should be fixed in 0.0.8
